[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
authors = ["jpglain"]
license = "MIT"

[dependencies]
chip8 = { path = "../chip8" }
log = "0.4"
fern = "0.6"
rfd = "0.9"
cpal = "0.13"
bincode = "1.3"
anyhow = "1.0.59"
eframe = "0.19"
